name: Build LiteView

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build for Linux
        run: |
          pyinstaller --onefile --noconsole ./main.py
        env:
          DISPLAY: ":0"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: liteview-linux
          path: dist/main

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build for Windows
        run: |
          pyinstaller --onefile --noconsole ./main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: liteview-windows
          path: dist/main.exe
