name: Build LiteView

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build for Linux
        run: |
          pyinstaller --onefile --noconsole ./main.py
        env:
          DISPLAY: ":0"

      - name: Upload artifact (for release)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/main
          asset_name: liteview-linux
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact (for all builds)
        if: "!startsWith(github.ref, 'refs/tags/') || always()"
        uses: actions/upload-artifact@v4
        with:
          name: liteview-linux
          path: dist/main
          if-no-files-found: error
          retention-days: 30
          compression-level: 6
          overwrite: true

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6

      - name: Build for Windows
        run: |
          pyinstaller --onefile --noconsole ./main.py

      - name: Upload artifact (for release)
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/main.exe
          asset_name: liteview-windows.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload artifact (for all builds)
        if: "!startsWith(github.ref, 'refs/tags/') || always()"
        uses: actions/upload-artifact@v4
        with:
          name: liteview-windows
          path: dist/main.exe
          if-no-files-found: error
          retention-days: 30
          compression-level: 6
          overwrite: true
